name: homelab

services:
  # Kafka

  kafka:
    image: apache/kafka:4.3.1
    container_name: homelab-kafka
    restart: unless-stopped
    volumes:
      - ./kafka/server.properties:/mnt/shared/config/server.properties:ro
      - ./data/kafka:/var/lib/kafka/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1",
        ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:v1.5.0
    container_name: homelab-kafka-ui
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: homelab-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy


  # ELK

  setup-elk:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.5.0
    container_name: homelab-setup-elk
    environment:
      ELASTIC_PASSWORD: elastic
      KIBANA_PASSWORD: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    command: >
      bash -c '
        until curl -fsS -u "elastic:$${ELASTIC_PASSWORD}" -H "Content-Type: application/json" -X POST http://elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"$${KIBANA_PASSWORD}\"}";
        do
          echo "Waiting for the Elasticsearch security index...";
          sleep 5;
        done
      '

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.5.0
    container_name: homelab-elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: "true"
      xpack.security.autoconfiguration.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      cluster.routing.allocation.disk.watermark.low: 10gb
      cluster.routing.allocation.disk.watermark.high: 5gb
      cluster.routing.allocation.disk.watermark.flood_stage: 2gb
      ELASTIC_PASSWORD: elastic
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS -u elastic:elastic 'http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s' >/dev/null",
        ]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 30s

  kibana:
    image: docker.elastic.co/kibana/kibana:9.5.0
    container_name: homelab-kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: kibana
    ports:
      - 5601:5601
    depends_on:
      setup-elk:
        condition: service_completed_successfully
