services:

  # https://github.com/bastienwirtz/homer
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ./config/homar:/www/assets # Make sure your local config directory exists
    ports:
      - ${HOMER_PORT}:8080
    environment:
      - INIT_ASSETS=1 # default, requires the config directory to be writable for the container user (see user option)
    restart: unless-stopped

  # https://hub.docker.com/r/linuxserver/qbittorrent
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=${TORRENT_WEBUI_PORT}
      - TORRENTING_PORT=6881
    volumes:
      - ./container_data/qbittorrent/appdata:/config
      - ~/media:/downloads/media
    ports:
      - ${TORRENT_WEBUI_PORT}:8080
      - ${TORRENT_TORRENTING_PORT}:${TORRENT_TORRENTING_PORT}
      - ${TORRENT_TORRENTING_PORT}:${TORRENT_TORRENTING_PORT}/udp
    restart: unless-stopped

  # https://jellyfin.org/docs/general/installation/container
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # network_mode: 'host'
    ports:
      - ${JELLYFIN_PORT}:8096
    volumes:
      - ./container_data/jellyfin/config:/config
      - ./container_data/jellyfin/cache:/cache
      - ~/media:/media
    restart: 'unless-stopped'

  # https://github.com/mishankov/web-tail
  web-tail:
    image: ghcr.io/mishankov/web-tail:main
    container_name: web-tail
    ports:
      - ${WEBTAIL_PORT}:4444
    volumes:
      - /var/log:/logs/system
      - ./config/web-tail/web-tail.config.toml:/app/web-tail.config.toml
    restart: 'unless-stopped'

  # https://github.com/mishankov/simple-system-monitor
  ssm:
    image: ghcr.io/mishankov/simple-system-monitor:main
    container_name: simple-system-monitor
    ports:
      - ${SSM_PORT}:4442
    env_file:
      - ./config/ssm/.env
    volumes:
      - /:/hostfs:ro
    restart: 'unless-stopped'

  # https://github.com/glanceapp/glance
  glance:
    container_name: glance
    image: glanceapp/glance
    volumes:
      - ./config/glance/config:/app/config
      - ./config/glance/assets:/app/assets
      # Optionally, also mount docker socket if you want to use the docker containers widget
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - ${GLANCE_PORT}:8080
    env_file: ./config/glance/.env
    restart: unless-stopped
