services:

  # https://github.com/bastienwirtz/homer
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ./config/homar:/www/assets # Make sure your local config directory exists
    ports:
      - 4444:8080
    environment:
      - INIT_ASSETS=1 # default, requires the config directory to be writable for the container user (see user option)
    restart: unless-stopped

  # https://hub.docker.com/r/linuxserver/qbittorrent
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./container_data/qbittorrent/appdata:/config
      - ~/media:/downloads/media
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  # https://jellyfin.org/docs/general/installation/container
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - ./container_data/jellyfin/config:/config
      - ./container_data/jellyfin/cache:/cache
      - ~/media:/media
    restart: 'unless-stopped'
