services:
  # https://github.com/mishankov/simple-system-monitor
  ssm:
    image: ghcr.io/mishankov/simple-system-monitor:main
    container_name: simple-system-monitor
    ports:
      - ${SSM_PORT}:4442
    env_file:
      - ./config/ssm/.env
    volumes:
      - /:/hostfs:ro
      - ./config/ssm/user-assets:/app/user-assets:ro
    restart: 'unless-stopped'

  # https://github.com/glanceapp/glance
  glance:
    container_name: glance
    image: glanceapp/glance
    platform: linux/arm64
    volumes:
      - ./config/glance/config:/app/config
      - ./config/glance/assets:/app/assets
      # Optionally, also mount docker socket if you want to use the docker containers widget
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - ${GLANCE_PORT}:8080
    env_file: ./config/glance/.env
    restart: unless-stopped
