services:
  proxymini:
    container_name: proxymini
    image: ghcr.io/mishankov/proxymini:main
    ports:
      - 14443:14443
    volumes:
      - ./config/proxymini/proxymini.conf.toml:/app/proxymini.conf.toml:ro
      - ./data:/app/data:rw
    restart: unless-stopped

  glance:
    container_name: glance
    image: glanceapp/glance
    volumes:
      - ./config/glance/config:/app/config
      - ./config/glance/assets:/app/assets
    ports:
      - ${GLANCE_PORT}:8080
    env_file: ./config/glance/.env
    restart: unless-stopped

  ssm:
    image: ghcr.io/mishankov/simple-system-monitor:main
    platform: linux/x86_64
    container_name: simple-system-monitor
    ports:
      - ${SSM_PORT}:4442
    env_file:
      - ./config/ssm/.env
    volumes:
      - /:/hostfs:ro
      - ./config/ssm/user-assets:/app/user-assets:ro
    restart: 'unless-stopped'
