services:
  installer:
    image: eclipse-temurin:11.0.31_11-jdk-jammy
    container_name: homelab-pega-installer
    command: ["./install-pega.sh"]
    volumes:
      - ./pega/distr:/distr
      - ./pega/application/postgresql-42.2.14.jar:/postgresql-42.2.14.jar
      - ./pega/installer/install-pega.sh:/install-pega.sh
      - ./pega/installer/init_pega.sql:/init_pega.sql
    depends_on:
      postgresql:
        condition: service_healthy
