---
# Homepage configuration
# See https://fontawesome.com/search for icons options

# Optional: Use external configuration file.
# Using this will ignore remaining config in this file
# externalConfig: https://example.com/server-luci/config.yaml

title: "Домашняя страница"
subtitle: ""
# documentTitle: "Welcome" # Customize the browser tab text
# Alternatively a fa icon can be provided:
# icon: "fas fa-skull-crossbones"

header: true # Set to false to hide the header
# Optional: Different hotkey for search, defaults to "/"
# hotkey:
#   search: "Shift"
footer: false # set false if you want to hide it.

columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example).
                        # You should set it to true when using an authentication proxy, it also reloads the page when a redirection is detected when checking connectivity.


# Set the default layout and color scheme
defaults:
  layout: columns # Either 'columns', or 'list'
  colorTheme: auto # One of 'auto', 'light', or 'dark'

# Optional theming
theme: default # 'default' or one of the themes available in 'src/assets/themes'.


# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Homer"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank"

# Services
# First level array represents a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Дом"
    icon: "fas fa-house"
    items:
      - name: "qBitorrent"
        icon: "fas fa-download"
        subtitle: "Качалка"
        url: "http://10.0.0.157:8080/"
        target: "_blank"

      - name: "Jellyfin"
        icon: "fas fa-play"
        subtitle: "Сериальчики"
        url: "http://10.0.0.157:8096/"
        target: "_blank"

  - name: "Внешние сервисы"
    icon: "fas fa-globe"
    items:
      - name: "RuTracker.org"
        icon: "fas fa-download"
        url: "https://rutracker.org/"
        target: "_blank"
