- name: Home
  width: slim
  hide-desktop-navigation: true
  center-vertically: true
  columns:
    - size: full
      widgets:
        - type: clock
          hour-format: 24h
          css-class: "no-header home-clock"

        - type: search
          search-engine: google
          autofocus: true
          new-tab: true
          css-class: "no-header"
          bangs:
            - title: GitHub
              shortcut: "!gh"
              url: https://github.com/search?q={QUERY}

        - type: bookmarks
          css-class: "no-header"
          groups:
            - title: General
              links:
                - title: Dev
                  url: /dev
                - title: Games
                  url: /games
                - title: Basketball
                  url: /basketball
            - title: Entertainment
              links:
                - title: YouTube
                  url: https://www.youtube.com/
            - title: Social
              links:
                - title: Github
                  url: https://github.com/
                - title: Reddit
                  url: https://www.reddit.com/
            - title: Infra
              links:
                - title: Uptime
                  url: https://uptime.mishankov.dev/dashboard
