- name: Fun
  columns:
    - size: full
      widgets:
      - type: group
        widgets:
          - type: reddit
            subreddit: lakers
            show-thumbnails: true
            show-flairs: true
            collapse-after: 15

          - type: reddit
            subreddit: nba
            show-thumbnails: true
            show-flairs: true
            collapse-after: 10

          - type: reddit
            subreddit: nbatalk
            show-thumbnails: true
            show-flairs: true
            collapse-after: 15

    - size: full
      widgets:
      - type: group
        widgets:
        - type: videos
          title: Basketball
          style: grid-cards
          channels:
            - UCpH_yPffJwMKWvS_Ncq862w # Daniel Li
            - UC3HPbvB6f58X_7SMIp6OPYw # Thinking Basketball
            - UCSpvjDk06HLxBaw8sZw7SkA # BBALLBREAKDOWN
            - UC3-gn89LFClSLU6scv9naOQ # Dom2k

        - type: videos
          style: grid-cards
          title: Games
          channels:
            - UC4yv7nCVHHmi1PiQk_VVifg # AshKing
            - UCq7JZ8ATgQWeu6sDM1czjhg # StopGmae
            - UC3G2Z2qfGoOzr8kSQYkFDaQ # StopGame Инфакт
            - UC1CchA0SjApw4T-AYkN7ytg # IGM
            - UCOmAtwe8UxKuj-qIdV77Iog # xDlate

- name: RSS
  columns:
    - size: full
      widgets:
        - type: rss
          title: RSS
          style: detailed-list
          feeds:
            - url: https://www.alexedwards.net/static/feed.rss
              title: Alex Edwards

            - url: https://www.joshwcomeau.com/rss.xml
              title: Josh Comeau
